# Generated by Django 4.2.3 on 2023-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myname", models.CharField(max_length=100)),
                ("mytitle", models.CharField(max_length=500)),
                ("mycontent", models.CharField(max_length=2000)),
                ("mydate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myname", models.CharField(max_length=100)),
                ("mypassword", models.CharField(max_length=100)),
                ("myemail", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=200)),
                ("dateTime", models.TextField(max_length=100)),
            ],
        ),
    ]
